version: "3"

networks:
  laravel:
services:

  php:
    build:
      context: .
      dockerfile: './docker/php/Dockerfile'
    container_name: 'php_swaggerL10'
    ports:
      - "9000:9000"
    volumes:
      - './:/var/www/html'
    networks:
      - laravel

  nginx:
    build:
      context: .
      dockerfile: './docker/nginx/Dockerfile'
    container_name: 'nginx_swaggerL10'
    ports:
      - "80:80"
    volumes:
      - './:/var/www/html'
    networks:
      - laravel

  db:
    image: mysql:latest
    container_name: 'mysql_swaggerL10'
    tty: true
    environment:
      MYSQL_USER: Revekka
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - './docker/mysql:/var/lib/mysql'
    networks:
      - laravel
